### ISSUE TITLE
WT specification

### ISSUE THREAD

**Issue by MarioGutierrezR** [krhyyme/ABA-Boolean-Network-Model#2]
Hi,
I ran the `KnockoutSimulations.py` script and I noticed that the output `knockouts.json` does not include a WT result. However, the `knockouts.json` that you used for the Plotting Tutorial does have the WT data. 
How do you specify that you also want the WT data? Should I create a new node in the input file?
I would appreciate your help!
Thanks,
Mario

**Comment by krhyyme** [comment]
Hello Mario,

I would specify a `WT` target [here](https://github.com/krhyyme/ABA-Boolean-Network-Model/blob/4ba3b05d94f05a6bd7ad9c7a2b2ac78b26ae7f12/KnockoutSimulations.py#L13). If the target doesn't match a node name in the network then the simulation returns the wild type response.

Best,
Karim

**Comment by krhyyme** [comment]
I'll also add that I'm happy to help with other questions. I've been working in Industry for the past 6 years so I might be hazy on the biology. But I will be able to answer any coding questions.

**Comment by MarioGutierrezR** [comment]
It worked, thanks for explaining it!
I'm actually working on a very similar topic, so I appreciate a lot your help.
I'll let you know if I come across other difficulties.

Mario
